language: node_js
node_js:
- '12'
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- npm install -g yarn # make sure yarn is new
- npm config set spin false
- npm install -g npm@^6.9.0
deploy:
  provider: npm
  email: iturgeon+npm@gmail.com
  on:
    tags: true
    repo: ucfopen/Materia-Widget-Dev-Kit
  api_key:
    secure: DirXS2I8L7cO7qZHQFpSqszV13UgfngjLa4XG76gQCiS0UelIB+7o9DuS6W0igCSEM7NH1emhXPplfoVOMWV4vWydAxzIJWTVgEU8osVDmYBUZz8835C+2x1exkGW49ekX/UQlRzpr7bNOdy0mbnnjPCExHNLgsMsgUrpqPcBh4qhM1kPCQgzSRym8vUOcmkFDIh4cXKa0tSVWsdCxBC9kjzvyDUvw+9hMA666J1PDuVQaPlgPc2DTBiQn3nONalIWNJ5Qlzfy5ezsbjqIUY3rfyi/ZR8HZoZuIrnNueDaHg9ONVRPWcCBPnncUSRxGmnr+hgKNNDKgyqaUPTdoCgRMCqt7pDJ8HjICQfbfDPr9PZJ4J5sfK2KVN6z1n9czVxfwxjf28uLNYT+Z2J/hOBTCzwfd06/538G15uWwEVzmYqBA2thpRxxAeQwhJn1T20XYdHKNycYFaQ110JbAsHWnDstlnWUL8TECY7tsK9y6p/TWbhmTscdU3VlEnMmSFcYDXHpzA9IwnHd9B+yLJRgMWJne4X09XDE/9uMMgnjpoF3w3g+NOhw1KU5VJGU4HbSXSmr9Ync3ded4WxQbBkuaeAFbTEbKV9Km0JZV5BtBkPGx7JayzAHZgmK6oDu1HhmFK3flihHURRm+QUnvks84FPw+KTEfScgV/JSMf9eM=
notifications:
  slack:
    secure: OCzINRvPDXExT8F5r8mq1C2H6qTiFmDVd5NBYcyg3uG6WnSKTGarwtcLrSR60TXar4WUsSnsZaqhhtF2toNbACepGlPt9XX7iECBYX7o/yupAxsz5Y0iCwOZobtNSuBEmr6X0G2WydoglrDi12onoE9ejU4TR0CQuNaeBRGC25TM+9p5BL+cvF6oNYXcvEXbEQddBfExCpoiVs/9Cg65w4dj9Yxttioe85hdluhcJIWSAcNQVOStacXOrf6wms1Wa7uwrcdili4Ub8DWy7GEVD/viffXnGffQmlruWc/GBzjTacw70NzxweCrv643Dgyi9Q+gLlmB7/tgF6x9tIhf0Ow4tJRrZMEGm4GVvRI1+tLx32SR0henl9fOPdRH81Db+R6UoGEwmhUiUbvtTsRnBxC33OBOuTqIeLW/DZOxDxbwj2oMIM12vFuRbXR/M0a23j82cXRsK41qZtAbtcXZW2BvJy5Kr0n4T9hMkzi/YEhsK3i+KWib2DnFKr/2W/ksk5uRe5z/RExpZpqFLqsBVSNF3LoGitvUQlsDZTs3uNuOCl14EMLENGSyqO8thGl5i5kwRVZc2YAQHcEMUJRa8q1XMRBVD4Y4IEls2DXeXNTdwqt2etYSBrfx1CmVqHcu6VfURrzQRltpdhm3KJ1vkEA+xK4VFQzu0slnBBSScA=
